<?php

return [
    'invoice' => [
        'Schweiz',
        'Deutschland',
        'Österreich',
        'Liechtenstein',
        'Afghanistan',
        'Ägypten',
        'Åland',
        'Albanien',
        'Algerien',
        'Amerikanisch-Samoa',
        'Amerikanische Jungferninseln',
        'Andorra',
        'Angola',
        'Anguilla',
        'Antigua und Barbuda',
        'Äquatorialguinea',
        'Argentinien',
        'Armenien',
        'Aruba',
        'Aserbaidschan',
        'Äthiopien',
        'Australien',
        'Bahamas',
        'Bahrain',
        'Bangladesch',
        'Barbados',
        'Belarus',
        'Belgien',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivien',
        'Bonaire, Saba, Sint Eustatius',
        'Bosnien und Herzegowina',
        'Botswana',
        'Bouvetinsel',
        'Brasilien',
        'Britische Jungferninseln',
        'Britisches Territorium im Indischen Ozean',
        'Brunei',
        'Bulgarien',
        'Burkina Faso',
        'Burundi',
        'Chile',
        'Volksrepublik China',
        'Cookinseln',
        'Costa Rica',
        'Curaçao',
        'Dänemark',
        'Dominica',
        'Dominikanische Republik',
        'Dschibuti',
        'Ecuador',
        'Elfenbeinküste',
        'El Salvador',
        'Eritrea',
        'Estland',
        'Eswatini',
        'Falklandinseln',
        'Färöer',
        'Fidschi',
        'Finnland',
        'Frankreich',
        'Französisch-Guayana',
        'Französisch-Polynesien',
        'Französische Süd- und Antarktisgebiete',
        'Gabun',
        'Gambia',
        'Georgien',
        'Ghana',
        'Gibraltar',
        'Grenada',
        'Griechenland',
        'Grönland',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guernsey (Kanalinsel)',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Heard und McDonaldinseln',
        'Honduras',
        'Hongkong',
        'Indien',
        'Indonesien',
        'Insel Man',
        'Irak',
        'Iran',
        'Irland',
        'Island',
        'Israel',
        'Italien',
        'Jamaika',
        'Japan',
        'Jemen',
        'Jersey (Kanalinsel)',
        'Jordanien',
        'Kaimaninseln',
        'Kambodscha',
        'Kamerun',
        'Kanada',
        'Kap Verde',
        'Kasachstan',
        'Katar',
        'Kenia',
        'Kirgisistan',
        'Kiribati',
        'Kokosinseln',
        'Kolumbien',
        'Komoren',
        'Kongo, Demokratische Republik',
        'Kongo, Republik',
        'Korea, Nord',
        'Korea, Süd',
        'Kroatien',
        'Kuba',
        'Kuwait',
        'Laos',
        'Lesotho',
        'Lettland',
        'Libanon',
        'Liberia',
        'Libyen',
        'Litauen',
        'Luxemburg',
        'Macau',
        'Madagaskar',
        'Malawi',
        'Malaysia',
        'Malediven',
        'Mali',
        'Malta',
        'Marokko',
        'Marshallinseln',
        'Martinique',
        'Mauretanien',
        'Mauritius',
        'Mayotte',
        'Mexiko',
        'Mikronesien',
        'Moldau',
        'Monaco',
        'Mongolei',
        'Montenegro',
        'Montserrat',
        'Mosambik',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Neukaledonien',
        'Neuseeland',
        'Nicaragua',
        'Niederlande',
        'Niger',
        'Nigeria',
        'Niue',
        'Nördliche Marianen',
        'Nordmazedonien',
        'Norfolkinsel',
        'Norwegen',
        'Oman',
        'Osttimor',
        'Pakistan',
        'Palästina',
        'Palau',
        'Panama',
        'Papua-Neuguinea',
        'Paraguay',
        'Peru',
        'Philippinen',
        'Pitcairninseln',
        'Polen',
        'Portugal',
        'Puerto Rico',
        'Réunion',
        'Ruanda',
        'Rumänien',
        'Russland',
        'Salomonen',
        'Saint-Barthélemy',
        'Saint-Martin (französischer Teil)',
        'Sambia',
        'Samoa',
        'San Marino',
        'São Tomé und Príncipe',
        'Saudi-Arabien',
        'Schweden',
        'Senegal',
        'Serbien',
        'Seychellen',
        'Sierra Leone',
        'Simbabwe',
        'Singapur',
        'Sint Maarten',
        'Slowakei',
        'Slowenien',
        'Somalia',
        'Spanien',
        'Sri Lanka',
        'St. Helena, Ascension und Tristan da Cunha',
        'St. Kitts und Nevis',
        'St. Lucia',
        'Saint-Pierre und Miquelon',
        'St. Vincent und die Grenadinen',
        'Südafrika',
        'Sudan',
        'Südgeorgien und die Südlichen Sandwichinseln',
        'Südsudan',
        'Suriname',
        'Spitzbergen und Jan Mayen',
        'Syrien',
        'Tadschikistan',
        'Tansania',
        'Thailand',
        'Togo',
        'Tokelau',
        'Tonga',
        'Trinidad und Tobago',
        'Tschad',
        'Tschechien',
        'Tunesien',
        'Türkei',
        'Turkmenistan',
        'Turks- und Caicosinseln',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'Ungarn',
        'United States Minor Outlying Islands',
        'Uruguay',
        'Usbekistan',
        'Vanuatu',
        'Vatikanstadt',
        'Venezuela',
        'Vereinigte Arabische Emirate',
        'Vereinigte Staaten',
        'Vereinigtes Königreich',
        'Vietnam',
        'Wallis und Futuna',
        'Weihnachtsinsel',
        'Westsahara',
        'Zentralafrikanische Republik',
        'Zypern',
    ],

    'delivery' => [
        'Schweiz',
        'Liechtenstein',
    ],

];
